<p style="float:right;"><i>Created By Maroyi Bisoka on 01/02/2025</i></p>

In [225]:
import numpy as np
import math
from copy import deepcopy

<div>
    <h2>Heart Disease Prediction Dataset</h2>
    <table border="1">
        <thead>
            <tr>
                <th>Age</th>
                <th>Cholesterol</th>
                <th>Blood Pressure</th>
                <th>Smoking</th>
                <th>Diabetes</th>
                <th>Exercise</th>
                <th>Heart Disease (Target)</th>
            </tr>
        </thead>
        <tbody>
            <tr><td>45</td><td>220</td><td>140</td><td>1</td><td>0</td><td>0</td><td>1</td></tr>
            <tr><td>52</td><td>180</td><td>130</td><td>0</td><td>1</td><td>1</td><td>1</td></tr>
            <tr><td>37</td><td>160</td><td>120</td><td>0</td><td>0</td><td>1</td><td>0</td></tr>
            <tr><td>60</td><td>250</td><td>150</td><td>1</td><td>1</td><td>0</td><td>1</td></tr>
            <tr><td>50</td><td>210</td><td>135</td><td>0</td><td>0</td><td>1</td><td>0</td></tr>
            <tr><td>48</td><td>190</td><td>125</td><td>1</td><td>0</td><td>1</td><td>0</td></tr>
            <tr><td>55</td><td>230</td><td>145</td><td>1</td><td>1</td><td>0</td><td>1</td></tr>
            <tr><td>42</td><td>170</td><td>120</td><td>0</td><td>0</td><td>1</td><td>0</td></tr>
            <tr><td>65</td><td>260</td><td>160</td><td>1</td><td>1</td><td>0</td><td>1</td></tr>
            <tr><td>58</td><td>200</td><td>140</td><td>0</td><td>1</td><td>1</td><td>1</td></tr>
        </tbody>
    </table>
</div>

In [227]:
# Features scaling 
def zscore_normalization(x):
    mu = np.mean(x, axis=0)
    sigma = np.std(x, axis=0)
    x_norm = (x - mu) / sigma      
    return x_norm, mu, sigma

In [228]:
def sigmoid(z):
    g = 1/(1+np.exp(-z))
    return g

In [229]:
def compute_cost(X, y, w, b):
    m = X.shape[0]
    cost = 0.0
    for i in range(m):
        z_i = np.dot(X[i], w) + b
        f_wb_i = sigmoid(z_i)
        cost +=  -y[i]*np.log(f_wb_i) - (1-y[i])*np.log(1-f_wb_i)
             
    cost /= m
    return cost

In [230]:
def compute_gradient(X, y, w, b):
    m, n = X.shape
    dj_dw = np.zeros(n)
    dj_db = 0.
    for i in range(m):
        f_wb_i = sigmoid(np.dot(X[i],w) + b)
        err_i = f_wb_i - y[i]
        for j in range(n):
            dj_dw[j] = dj_dw[j] + err_i * X[i,j]
        dj_db = dj_db + err_i
    dj_dw /= m
    dj_db /= m
    return dj_dw, dj_db

In [231]:
def gradient_descent(X, y, w_init, b_init, epochs, alpha):
    w = deepcopy(w_init)
    b = b_init
    for i in range(epochs):
        dj_dw, dj_db = compute_gradient(X, y, w, b) # Compute gradient
        # Update w and b
        w = w - alpha * dj_dw
        b = b - alpha * dj_db

        if i% math.ceil(epochs / 10) == 0:
            print(f"Iteration {i:4d}: Cost {compute_cost(X, y, w, b)}")

    return w, b

In [232]:
# Training dataset
X_train = np.array([
    [45, 220, 140, 1, 0, 0],
    [52, 180, 130, 0, 1, 1],
    [37, 160, 120, 0, 0, 1],
    [60, 250, 150, 1, 1, 0],
    [50, 210, 135, 0, 0, 1],
    [48, 190, 125, 1, 0, 1],
    [55, 230, 145, 1, 1, 0],
    [42, 170, 120, 0, 0, 1],
    [65, 260, 160, 1, 1, 0],
    [58, 200, 140, 0, 1, 1]
])
y_train = np.array([1, 1, 0, 1, 0, 0, 1, 0, 1, 1])

In [233]:
m, n = X_train.shape
w_init = np.zeros(n)
b_init = 0.0
epochs = 1_000
alpha = 1e-1

In [234]:
# Perform feature scaling 
X_norm, mu, sigma = zscore_normalization(X_train)

In [235]:
X_norm

array([[-0.75995002,  0.4108907 ,  0.28090032,  1.        , -1.        ,
        -1.22474487],
       [ 0.09805807, -0.85338838, -0.52167203, -1.        ,  1.        ,
         0.81649658],
       [-1.7405307 , -1.48552792, -1.32424438, -1.        , -1.        ,
         0.81649658],
       [ 1.07863874,  1.35910001,  1.08347268,  1.        ,  1.        ,
        -1.22474487],
       [-0.1470871 ,  0.09482093, -0.12038585, -1.        , -1.        ,
         0.81649658],
       [-0.39223227, -0.53731861, -0.92295821,  1.        , -1.        ,
         0.81649658],
       [ 0.46577582,  0.72696047,  0.6821865 ,  1.        ,  1.        ,
        -1.22474487],
       [-1.12766778, -1.16945815, -1.32424438, -1.        , -1.        ,
         0.81649658],
       [ 1.69150167,  1.67516978,  1.88604503,  1.        ,  1.        ,
        -1.22474487],
       [ 0.83349357, -0.22124884,  0.28090032, -1.        ,  1.        ,
         0.81649658]])

In [236]:
# Training model
w_final, b_final = gradient_descent(X_norm, y_train, w_init, b_init, epochs, alpha)

Iteration    0: Cost 0.6301383314649103
Iteration  100: Cost 0.1548919881318656
Iteration  200: Cost 0.1014638508204114
Iteration  300: Cost 0.07494235705239713
Iteration  400: Cost 0.05907695668610705
Iteration  500: Cost 0.048581693062498564
Iteration  600: Cost 0.04115860071596451
Iteration  700: Cost 0.0356487011023929
Iteration  800: Cost 0.03140644707240077
Iteration  900: Cost 0.028045046952733237


In [237]:
# w_final and b_final
print(f'w_final {w_final}')
print(f'b_final {b_final}')

w_final [ 0.53103561  0.10499975  1.29731831  0.35885547  3.03829102 -2.26896494]
b_final 2.423610153636453


In [238]:
def predict_with_norm_value(X_test, w, b, threshold, mu, sigma, sigmoid_function):
    m = X_test.shape[0]
    X_norm_test = (X_test - mu) / sigma
    pred = np.zeros(m, dtype=int)
    for i in range(m):
        z = np.dot(X_norm_test[i], w) + b
        g = sigmoid_function(z)
        pred[i] = 1 if g >= threshold else 0
    return pred

In [239]:
# Predictions of our own implementation
threshold = 0.5
predictions = predict_with_norm_value(X_train, w_final, b_final, threshold, mu, sigma, sigmoid)
predictions

array([1, 1, 0, 1, 0, 0, 1, 0, 1, 1])

In [240]:
y_train

array([1, 1, 0, 1, 0, 0, 1, 0, 1, 1])

## Use sklearn for testing our own implementation
<p>
    Scikit-learn (sklearn) is an open-source machine learning library for Python that provides implementations of numerous data modeling and machine learning algorithms, and provides consistent Python APIs. It supports a standardized and concise model interface across models.
</p>

In [242]:
from sklearn.linear_model import LogisticRegression

In [243]:
logmodel = LogisticRegression(max_iter=1_000)

In [244]:
logmodel.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [245]:
sklearn_pred = logmodel.predict(X_train)

In [246]:
# Prediction of Sklearn
sklearn_pred

array([1, 1, 0, 1, 0, 0, 1, 0, 1, 1])

In [247]:
#Our prediction
predictions

array([1, 1, 0, 1, 0, 0, 1, 0, 1, 1])

# Testing on new dataset

In [249]:
X_test = np.array([
    [46, 200, 130, 1, 0, 1],
    [53, 210, 140, 0, 1, 0],
    [39, 170, 120, 0, 0, 1],
    [62, 240, 150, 1, 1, 0],
    [49, 195, 128, 0, 0, 1]
])
y_test = np.array([1, 1, 0, 1, 0])

In [250]:
# Testing our implementation
pred_test = predict_with_norm_value(X_test, w_final, b_final, threshold, mu, sigma, sigmoid)

In [251]:
print(f'y_test:    {y_test}')
print(f'pred_test: {pred_test}')

y_test:    [1 1 0 1 0]
pred_test: [0 1 0 1 0]


In [252]:
# Testing sklearn implementation
sk_pred_test = logmodel.predict(X_test)

In [253]:
print(f'y_test:       {y_test}')
print(f'sk_pred_test: {pred_test}')

y_test:       [1 1 0 1 0]
sk_pred_test: [0 1 0 1 0]


In [254]:
# Evaluation
from sklearn.metrics import classification_report

In [255]:
report = classification_report(y_test, sk_pred_test)

In [256]:
print(report)

              precision    recall  f1-score   support

           0       0.67      1.00      0.80         2
           1       1.00      0.67      0.80         3

    accuracy                           0.80         5
   macro avg       0.83      0.83      0.80         5
weighted avg       0.87      0.80      0.80         5

