<p style="float:right;"><i>Created By Maroyi Bisoka on 01/02/2025</i></p>

In [1320]:
import numpy as np

**A dense layer**, also known as a fully connected layer, is a type of neural network layer where every neuron in the layer is connected to every neuron in the previous layer. This connectivity allows each neuron to receive input from all neurons in the preceding layer.

<img src="./neural_network_img.png" style="width: 400px; height: auto;">

In [1323]:
# Activation function --> Sigmoid 
def sigmoid(z):
    g = 1 / (1 + np.exp(-z))
    return g

In [1324]:
# Compute the activation function of each neuron within a single Layer
def dense(a_in, W, b, activation_function):
    no_neurons = W.shape[1]
    a_out = np.zeros(no_neurons)
    for j in range(no_neurons):
        w = W[:, j]
        z = np.dot(a_in, w) + b[j]
        a_out[j] = activation_function(z)
    return a_out

In [1325]:
# Compute the forward propagation algorithm
def sequential(x, W_list, b_list, activation_function):
    no_layers = len(W_list)
    a_in  = x
    for i in range(no_layers):
        a_out = dense(a_in, W_list[i], b_list[i], activation_function)
        a_in = a_out
    return a_out

In [1326]:
# Random initialization of the value of x
np.random.seed(1)
X_test = np.random.randint(-100, 100, size=(5,2))
X_test

array([[-63,  40],
       [-28,  37],
       [ 33, -21],
       [ 92,  44],
       [ 29, -29]])

In [1327]:
# Random initialization for the parameters W and b

l1_shape = (2,2) # layer1_shape (number of W in a single neurons, number of neurons)
l2_shape = (2,1) # layer2_shape (number of W in a single neurons, number of neurons)

np.random.seed(10) # used to generate same random number
W1 = np.random.rand(l1_shape[0], l1_shape[1])

np.random.seed(20)
b1 =  np.random.rand(l1_shape[1])

np.random.seed(30) 
W2 = np.random.rand(l2_shape[0], l2_shape[1])

np.random.seed(40) 
b2 = np.random.rand(l2_shape[1])

In [1328]:
W1, b1

(array([[0.77132064, 0.02075195],
        [0.63364823, 0.74880388]]),
 array([0.5881308 , 0.89771373]))

In [1329]:
# W1 means all the w for layer 1
# W1_1 means all the w for the 1st layer 1st neuron
W1_1 = W1[:, 0]
print('W1_1: ', W1_1)
# W1_2 means all the w for the 1st layer 2nd neuron
W1_2= W1[:, 1]
print('W1_2: ', W1_2)

W1_1:  [0.77132064 0.63364823]
W1_2:  [0.02075195 0.74880388]


In [1330]:
W2, b2

(array([[0.64414354],
        [0.38074849]]),
 array([0.40768703]))

In [1331]:
# W2 means all the w for layer 2
# W2_1 means all the w for the 2nd layer 1st neuron
W2_1 = W2[:, 0]
print('W2_1: ', W2_1)

W2_1:  [0.64414354 0.38074849]



<br />
<hr />

**NB**: All of the rows of a specific col within a W matrix specify the w's of a specific neuron.

For example: 
- If we're looking for the w's of the 1st layer 1st neuron --> **W1[: , 0]** we used **':'** for the row to get all the row and **'0'** for the column since python indexing start from zero (neuron 1 at index 0, neuron 2 at index 1, and so on).
- If we're looking for the w's of the 1st layer 2nd neuron  --> **W1[: , 1]**
- If we're looking for the w's of the 2nd layer 1st neuron  --> **W2[: , 0]**
- If we're looking for the b of the 1st layer 2nd neuron  --> **b1[1]**



In [1333]:
W_list = [W1, W2]
b_list = [b1, b2]

In [1334]:
# Running Forward propagation for a single test example
sequential(X_test[0], W_list, b_list, sigmoid)

array([0.68749531])

In [1335]:
def predict(X_test, W_list, b_list, sigmoid):
    m = X_test.shape[0]
    a_out = np.zeros(m)
    for i in range(m):
        a_out[i] = sequential(X_test[i], W_list, b_list, sigmoid)
    return a_out

In [1336]:
# Running Forward propagation for whole test examples
a_out = predict(X_test, W_list, b_list, sigmoid)

In [1337]:
a_out

array([0.68749531, 0.79911181, 0.74112595, 0.80730284, 0.73987059])

## Checking with Tensorflow

In [1339]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [1340]:
model = Sequential(
    [
        tf.keras.Input(shape=(2,)), # means number of features
        Dense(2, activation='sigmoid', name = 'layer1'), # (Number of neurons, Activation function, Name of the Layer)
        Dense(1, activation='sigmoid', name = 'layer2'),  # (Number of neurons, Activation function, Name of the Layer)
     ]
)

In [1341]:
model.summary()

Model: "sequential_17"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ layer1 (Dense)                  │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ layer2 (Dense)                  │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [1342]:
# Setting W and b for layer 1
model.get_layer('layer1').set_weights([W1, b1])
print('W of layer1 (W1): ')
print(model.get_layer('layer1').weights[0].numpy())
print('-------------------------')
print('b of layer1 (b1): ')
print(model.get_layer('layer1').weights[1].numpy())

W of layer1 (W1): 
[[0.77132064 0.02075195]
 [0.6336482  0.74880385]]
-------------------------
b of layer1 (b1): 
[0.5881308 0.8977137]


In [1343]:
# Setting W and b for layer 2
model.get_layer('layer2').set_weights([W2, b2])
print('W of layer2 (W2): ')
print(model.get_layer('layer2').weights[0].numpy())
print('-------------------------')
print('b of layer2 (b2): ')
print(model.get_layer('layer2').weights[1].numpy())

W of layer2 (W2): 
[[0.6441435 ]
 [0.38074848]]
-------------------------
b of layer2 (b2): 
[0.40768704]


In [1344]:
# Tensorflow prediction
model.predict(X_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step


array([[0.68749535],
       [0.7991118 ],
       [0.74112594],
       [0.80730283],
       [0.7398706 ]], dtype=float32)

In [1345]:
# Our own implemetation prediction
a_out

array([0.68749531, 0.79911181, 0.74112595, 0.80730284, 0.73987059])