<p style="float:right;"><i>Created By Maroyi Bisoka on 01/02/2025</i></p>

In [539]:
import numpy as np

**A dense layer**, also known as a fully connected layer, is a type of neural network layer where every neuron in the layer is connected to every neuron in the previous layer. This connectivity allows each neuron to receive input from all neurons in the preceding layer.

<img src="./neural_network_img.png" style="width: 400px; height: auto;">

In [542]:
# Activation function Choosed: Sigmoid 
def sigmoid(z):
    g = 1 / (1 + np.exp(-z))
    return g

In [543]:
# Compute the activation function of each neuron within a single Layer
def dense(a_in, W, b, activation_function):
    no_neurons = W.shape[1]
    a_out = np.zeros(no_neurons)
    for j in range(no_neurons):
        w = W[:, j]
        z = np.dot(a_in, w) + b[j]
        a_out[j] = activation_function(z)
    return a_out

In [544]:
# Compute the forward propagation algorithm
def sequential(x, W_list, b_list, activation_function):
    no_layers = len(W_list)
    a_in  = x
    for i in range(no_layers):
        a_out = dense(a_in, W_list[i], b_list[i], activation_function)
        a_in = a_out
    return a_out

In [545]:
# Random initialization of the value of x
np.random.seed(1)
x = np.random.randint(0, 20, size=2)
x

array([ 5, 11])

In [546]:
# Random initialization for the parameters W and b

l1_shape = (2,2) # layer1_shape (number of W in a single neurons, number of neurons)
l2_shape = (2,1) # layer2_shape (number of W in a single neurons, number of neurons)

np.random.seed(10) # used to generate same random number
W1 = np.random.rand(l1_shape[0], l1_shape[1])

np.random.seed(20)
b1 =  np.random.rand(l1_shape[1])

np.random.seed(30) 
W2 = np.random.rand(l2_shape[0], l2_shape[1])

np.random.seed(40) 
b2 = np.random.rand(l2_shape[1])

In [547]:
W1, b1

(array([[0.77132064, 0.02075195],
        [0.63364823, 0.74880388]]),
 array([0.5881308 , 0.89771373]))

In [548]:
# W1 means all the w for layer 1
# W1_1 means all the w for the 1st layer 1st neuron
W1_1 = W1[:, 0]
print('W1_1: ', W1_1)
# W1_2 means all the w for the 1st layer 2nd neuron
W2_1= W1[:, 1]
print('W2_1: ', W2_1)

W1_1:  [0.77132064 0.63364823]
W2_1:  [0.02075195 0.74880388]


In [549]:
W2, b2

(array([[0.64414354],
        [0.38074849]]),
 array([0.40768703]))

In [550]:
# W2 means all the w for layer 2
# W2_1 means all the w for the 2nd layer 1st neuron
W1_1 = W2[:, 0]
print('W1_1: ', W1_1)

W1_1:  [0.64414354 0.38074849]



<br />
<hr />

**NB**: All of the rows of a specific col within a W matrix specify the w's of a specific neuron.

For example: 
- If we're looking for the w's of the 1st layer 1st neuron --> **W1[: , 0]** we used **':'** for the row to get all the row and **'0'** for the column since python indexing start from zero (neuron 1 at index 0, neuron 2 at index 1, and so on).
- If we're looking for the w's of the 1st layer 2nd neuron  --> **W1[: , 1]**
- If we're looking for the w's of the 2nd layer 1st neuron  --> **W2[: , 0]**
- If we're looking for the b of the 1st layer 2nd neuron  --> **b1[1]**



In [552]:
W_list = [W1, W2]
b_list = [b1, b2]

In [553]:
# Running Forward propagation
a_out = sequential(x, W_list, b_list, sigmoid)

In [554]:
# Output Layer value
a_out

array([0.80729598])